"$schema" = "./node_modules/wrangler/config-schema.json"
name = "doit-web"
main = ".open-next/worker.js"
compatibility_date = "2026-04-08"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[triggers]
crons = ["*/5 * * * *"]

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://wimpnybtdqgsszgibxvh.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable__zkroZ9WBRL0wHTV4JFY0w_GDm0Ng0q"
NEXT_PUBLIC_APP_URL = "https://doit-web.mir24.workers.dev"
NOTIFICATION_EMAIL_FROM = "Doit <onboarding@resend.dev>"